const courses = [
  {
    name: 'Объектно-ориентированное и визуальное программирование',
    language: 'C#',
    article: 'Методическое пособие',
    count: 17,
    folder: 'oop',
    links: [
      'https://docs.google.com/document/d/1M7er5Ay3ze-e14CsCuH4s0jnjrPdTsksdes5uB_UYZw/edit?usp=drive_link',
      'https://docs.google.com/document/d/1nMc6X6xd770d8phOfvXKP_R42I-WqminU_kN3JbqVBw/edit?usp=drive_link',
      'https://docs.google.com/document/d/1KAqBg05kzYoncwtQXFTStx32oA4QLxg9_bdbR_qE904/edit?usp=drive_link',
      'https://docs.google.com/document/d/1G6gcGrLsKu8GbVIJaw6HGy3kdTCaRL71jcCdD8lylxY/edit?usp=drive_link',
      'https://docs.google.com/document/d/1HyrC-HY86rK8zWjn6QXaGgA41Soxoy1BoMCzzWt9X4o/edit?usp=drive_link',
      'https://docs.google.com/document/d/196WljgtwmOOaOMt74tGQio2KSM-qkbj58eyjMB8oxJc/edit?usp=drive_link',
      'https://docs.google.com/document/d/11CDLYyXKYbj_1XGVqBcuC0tmPsIx2TK4iRJWyAySAOY/edit?usp=drive_link',
      'https://docs.google.com/document/d/1M53eC3z6YV3ufRZqClIAg0k6WlgbBAf1KFTt7cHWicc/edit?usp=drive_link',
      'https://docs.google.com/document/d/1nP4_gQov68gwzVDxHNAgQ0QxiXwD2WqiKBTimMyeVH4/edit?usp=drive_link',
      'https://docs.google.com/document/d/1BKZ03Wnin2975tYGaJQ656BvruO-jaL_AaossJ0VGY4/edit?usp=drive_link',
      'https://docs.google.com/document/d/1TNhaunWsWNVk_k0tfSz2gLEBHAfSVcC0C_kDK4Gd8y8/edit?usp=drive_link',
      'https://docs.google.com/document/d/1AOWQeMb8j6lWpelv9VUGyEOPp4UTj2UFA7JCO3H8bfw/edit?usp=drive_link',
      'https://docs.google.com/document/d/16cZzpypHaAjnJRCxB5HLDIXT2zFPYrGGmdNALFxsui0/edit?usp=drive_link',
      'https://docs.google.com/document/d/1mSkbnsili-XroDI0CdVX83WdnrP4e0p_6Us5vgVmeT0/edit?usp=drive_link',
      'https://docs.google.com/document/d/1O4TXgaIovV7eiFlBaM-iIhD-CZ9EdJzEJF0bp_BrCr0/edit?usp=drive_link',
      'https://docs.google.com/document/d/1jau2wzSsKmnJ6m24qlxiutbMvnJ7WaoPmCFkhTS4nZY/edit?usp=drive_link',
      'https://docs.google.com/document/d/1KtFuwEeTbdB1kag0b_8T-P1429AxKefU7O-nY23Tzvo/edit?usp=drive_link',
    ],
  },
  {
    name: 'Структуры и алгоритмы компьютерной обработки данных',
    language: 'C#',
    article: 'Методическое пособие.',
    count: 7,
    folder: 'sacod',
    links: [
      'https://docs.google.com/document/d/188jU7eXi4B3C3mhcsUuVK0ATdoMsTMyfPL1Bw5OIJMY/edit?usp=drive_link',
      'https://docs.google.com/document/d/1EZJxqUWITDy_GhZ39ipedc4JTgBaPTJ8AyOP7_n27KM/edit?usp=drive_link',
      'https://docs.google.com/document/d/15r16GC2NIx1-Hh4QiRj2bupgPq3WiBH4FeHF9nvjveI/edit?usp=drive_link',
      'https://docs.google.com/document/d/1oO770CRz1fxnXMNfQr9vNdiYd5Ay0MMSBThVB4j58EI/edit?usp=drive_link',
      'https://docs.google.com/document/d/1z24lEGv8KO3nh-ymDSfrChd3zVKV8j1LBnmFAvskOJU/edit?usp=drive_link',
      'https://docs.google.com/document/d/1Li6ytLL4ZteLHL2yJy7JWjbl23V03NQYCVUbc6F82hQ/edit?usp=drive_link',
      'https://docs.google.com/document/d/1nGCvNb85kW1y2AUv0I8F60dXLbCK_fMnTZJR9v9MaKs/edit?usp=drive_link',
      'https://docs.google.com/document/d/1r22avAvYbGQYuQp6ESjC4yFse1jUHLIUvHqtYx2ym_Q/edit?usp=drive_link',
      'https://docs.google.com/document/d/173m-aVc-h3t0rJvsk7SiatEsO4VulD80vds5yilntjA/edit?usp=drive_link',
      'https://docs.google.com/document/d/1swfiAYa2_YQSEY9ZvmXgKH49-oPgcVrk4Nyr4JqG3GA/edit?usp=drive_link',
    ],
  },
  {
    name: 'Язык программирования Python',
    language: 'Python',
    article: 'Методическое пособие.',
    count: 15,
    folder: 'python',
    links: [
      'https://docs.google.com/document/d/1AJ1P0F8edoAJzJFgnMGGTew_xPyl5cXB/edit?usp=drive_link',
      'https://docs.google.com/document/d/1RgMgxCYGkOslECw67JffYSK4Vurcayr2/edit?usp=drive_link',
      'https://docs.google.com/document/d/1gmAiUVcuKBpdSMwDc--Qia7mkHImyaOJ/edit?usp=drive_link',
      'https://docs.google.com/document/d/1G2Op5tkuDWsx3b-f0WTTUj_CCtdY58cB/edit?usp=drive_link',
      'https://docs.google.com/document/d/1Y9tGMLxs-dMkDiONU6kEY8EJ-lzX0FBl/edit?usp=drive_link',
      'https://docs.google.com/document/d/11L98JIlW-jubnNko_mwkEXUCaUMoAdPn/edit?usp=drive_link',
      'https://docs.google.com/document/d/1hihqUFfQMmKOLozTDPadrBhllV-meK2L/edit?usp=drive_link',
      'https://docs.google.com/document/d/1PY666z0hbF7YJalQYWt9uo8Qne5cTJSH/edit?usp=drive_link',
      'https://docs.google.com/document/d/1YIQusLyBatp72sA0VNUPAwSYIMwbezjU/edit?usp=drive_link',
      'https://docs.google.com/document/d/1oScH99h4ulRCjllPL_8z0jq5nPBPt352/edit?usp=drive_link',
      'https://docs.google.com/document/d/1Htp9qzn20_giNT2UK0vk83sML6skeovI/edit?usp=drive_link',
      'https://docs.google.com/document/d/1eubcIYp9dDfq5HPqIi1o1a16Ha-9i8XP/edit?usp=drive_link',
      'https://docs.google.com/document/d/1HOyVDfV2L38edGS9NL1fnDYX_ypIa0cs/edit?usp=drive_link',
      'https://docs.google.com/document/d/1SsT9o-qa6Az1S3Xuwi7QSwLkX894SV89/edit?usp=drive_link',
      'https://docs.google.com/document/d/15WhK4UP8Yih6YtvVxCfK178PUjeqOt7C/edit?usp=drive_link',
    ],
  },
  {
    name: 'Структуры данных в языке Python',
    language: 'Python',
    article: 'Методическое пособие.',
    count: 17,
    folder: 'python-2',
    links: [
      'https://docs.google.com/document/d/13NMiSX0EoywWm7aTbSY2DZy6MO2Cmmgd/edit?usp=drive_link',
      'https://docs.google.com/document/d/12bD1lJA4xg9XEvgRCiInPObf9AIVkfIl/edit?usp=drive_link',
      'https://docs.google.com/document/d/1lVPvNTdjRstgXnqpI7LkWY4QZzsMGaI3/edit?usp=drive_link',
      'https://docs.google.com/document/d/1sgFAQCqBv0fFOD0glcXXmqCwQp8Y3NjK/edit?usp=drive_link',
      'https://docs.google.com/document/d/1vAuqDlrdA0B0zf57AJ875zfssmn7a7ig/edit?usp=drive_link',
      'https://docs.google.com/document/d/1llXdXHngsZNMRhyqS5-JkJzozznU2KGH/edit?usp=drive_link',
      'https://docs.google.com/document/d/1KlDg35RstHVr7Lm75nWMulPOdgYgBK08/edit?usp=drive_link',
      'https://docs.google.com/document/d/1efUJWU5bU2_2_FRRKZfeuKbMuOXt8uQB/edit?usp=drive_link',
      'https://docs.google.com/document/d/1xTXSULB-0sg1LadsVbpS0Ed7u0YHoWOZ/edit?usp=drive_link',
      'https://docs.google.com/document/d/1U5b0pb-la24l9Ovz9X3Sz0o3qrXbwpoD/edit?usp=drive_link',
      'https://docs.google.com/document/d/13ZifTUdbiVaTQ-nw6_suQQBSjxN8AIto/edit?usp=drive_link',
      'https://docs.google.com/document/d/11-2KNZ0r319O4cnNKvv8EqLJuHdA_LN8/edit?usp=drive_link',
      'https://docs.google.com/document/d/1j9cDiLuHNxfSFiNMEysEpr3FGh_ERvJi/edit?usp=drive_link',
      'https://docs.google.com/document/d/1OndBXZVFck6Tg3YExu0OIvu1hHpLZ6TR/edit?usp=drive_link',
      'https://docs.google.com/document/d/17kDGniJL3-6ieFwDHwW9IFT7rUPRKC6D/edit?usp=drive_link',
      'https://docs.google.com/document/d/1UhW6AsSR6UyT-NY5wawUw3OZg_vtrvp6/edit?usp=drive_link',
      'https://docs.google.com/document/d/1tze-8TGSid5mGi4E7lxvCf43YUbLXprf/edit?usp=drive_link',
    ],
  },
  {
    name: 'Объектно-ориентированное программирования в языке Python',
    language: 'Python',
    article: 'Методическое пособие.',
    count: 5,
    folder: 'python-3',
    links: [
      'https://docs.google.com/document/d/1qYxg5ksbOm3l2Wd3ecdvtA1-ccEupBuB/edit?usp=drive_link',
      'https://docs.google.com/document/d/1yHxut4SFd8JFgf745spF-Y4Z4DhP4sBh/edit?usp=drive_link',
      'https://docs.google.com/document/d/1WVdCIIHsl5feHWSdnACDY6dwl8NElaFM/edit?usp=drive_link',
      'https://docs.google.com/document/d/11iE79eUvqZkTjDipx57j3AlBcNS0lw-K/edit?usp=drive_link',
      'https://docs.google.com/document/d/1xf8gnQqTsWwQDjmEI6b098UfZmOLnLij/edit?usp=drive_link',
    ],
  },
  {
    name: 'Параллельное и распреленное программирование',
    language: 'C#',
    article: 'Методическое пособие.',
    count: 17,
    folder: 'oop',
    links: [
      '1',
      '2',
      '3'
    ],
  },
  {
    name: 'Технологии разработки программного обеспечения',
    language: 'C#',
    article: 'Методическое пособие.',
    count: 17,
    folder: 'oop',
    links: [
      '1',
      '2',
      '3'
    ],
  },
  {
    name: 'Метрология и качество программного обеспечения',
    language: 'C#',
    article: 'Методическое пособие.',
    count: 17,
    folder: 'oop',
    links: [
      '1',
      '2',
      '3'
    ],
  },
  {
    name: 'Язык программирования JavaScript',
    language: 'JavaScript',
    article: 'Методическое пособие.',
    count: 17,
    folder: 'oop',
    links: [
      '1',
      '2',
      '3'
    ],
  },
  {
    name: 'Технологии разработки пользовательского интерфейса',
    language: 'HTML',
    article: 'Методическое пособие.',
    count: 17,
    folder: 'oop',
    links: [
      '1',
      '2',
      '3'
    ],
  },
]

export default courses;